---

- block:
    - when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - setup-oxitraffic
    - install-all
    - install-oxitraffic

- block:
    - when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-oxitraffic
    - install-all
    - install-oxitraffic

- block:
    - when: not oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-oxitraffic

- block:
    - when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/migrate_0.7_to_0.8.yml"
  tags:
    - setup-all
    - setup-oxitraffic
    - install-all
    - install-oxitraffic
