# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform OxiTraffic installation tasks
  when: oxitraffic_enabled | bool
  tags:
    - setup-all
    - setup-oxitraffic
    - install-all
    - install-oxitraffic
  block:
    - name: Validate OxiTraffic configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install OxiTraffic
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
    - name: Migrate OxiTraffic 0.7 to 0.8
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/migrate_0.7_to_0.8.yml"

- name: Perform OxiTraffic uninstallation tasks
  when: not oxitraffic_enabled | bool
  tags:
    - setup-all
    - setup-oxitraffic
  block:
    - name: Uninstall OxiTraffic
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
