# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform OxiTraffic installation tasks
  block:
    - name: Validate OxiTraffic configuration
      when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install OxiTraffic
      when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

    - name: Migrate OxiTraffic 0.7 to 0.8
      when: oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/migrate_0.7_to_0.8.yml"
  tags:
    - setup-all
    - setup-oxitraffic
    - install-all
    - install-oxitraffic

- name: Perform OxiTraffic uninstallation tasks
  block:
    - name: Uninstall OxiTraffic
      when: not oxitraffic_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-oxitraffic
